#!/bin/sh

set -eu

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)

cd "${ROOT_DIR}"

echo "Building frontend..."

# Install the dependencies
npm install

# Run the compilers
npm run tsc
npm run sass

echo "Backend will be built by CloudFoundry"
