#!/bin/sh

set -eu

PROJECT_DIR=$(cd "$(dirname "$0")/../" && pwd)
CURRENT_DIR=$(pwd)

export CF_APP_NAME=rubbernecker
export CF_API
export CF_APPS_DOMAIN

export PIVOTAL_TRACKER_PROJECT_ID=`cat "../secrets/${SECRETS_FILE}" | awk '/pivotal_tracker_project_id/ { print $2 }'`
export PIVOTAL_TRACKER_API_TOKEN=`cat "../secrets/${SECRETS_FILE}" | awk '/pivotal_tracker_api_token/ { print $2 }'`
export PAGERDUTY_AUTHTOKEN=`cat "../secrets/${SECRETS_FILE}" | awk '/pagerduty_authtoken/ { print $2 }'`

cd ${PROJECT_DIR}

echo "Creating ${CF_APP_NAME} manifest"
release/generate-manifest \
    < manifest.yml \
    > modified_manifest.yml

echo "Deploying ${CF_APP_NAME} with zero downtime"
cf zero-downtime-push ${CF_APP_NAME} \
    -f modified_manifest.yml

cd ${CURRENT_DIR}
