on: pull_request

env:
  GO_VERSION: "1.20"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Tests
        run: "make test"
